### ISSUE TITLE
Use CLI Credentials to connect to Managed HSM

### ISSUE THREAD

**Issue by svenkata9** [microsoft/AzureKeyVaultManagedHSMEngine#14]
Hi folks @liupums  @chkimes @mattsains, This repo is what exactly I was looking for, for using openssl to access the Managed HSM or Key Vault.

Is there a way to use CLI Credentials to use the Managed HSM for signing? Currently it depends on Managed Identity. I have given access to my login as Managed HSM Crypto User to /keys and that should suffice to accessing the managed HSM. Could you please help? (Azure SDK for Python's hello_world.py example can use AzureCLICredential to create keys in HSM, and sign is also an operation supported by the SDK (as per documentation). Thanks.

Here is a screenshot:

![image](https://user-images.githubusercontent.com/29835993/194355119-6a1bbdc6-4b5d-4510-914a-e4dcc867d00d.png)

**Comment by liupums** [comment]
The support is added for windows only, doc is here
https://github.com/microsoft/AzureKeyVaultManagedHSMEngine/blob/main/samples/openssl/UseAzureCliCredential.md
