### ISSUE TITLE
Is this engine work with openssl 3.0? 

### ISSUE THREAD

**Issue by jetbee** [microsoft/AzureKeyVaultManagedHSMEngine#4]
Hello, there.

Is this engine work with openssl 3.0?
I'm worried about this engine uses deprecated functions or not.
If it works with 3.0, is there some method to compile with openssl 3.0?

**Comment by liupums** [comment]
This engine is NOT working for openssl 3.0. In OpenSSL 3.0, dynamic engine is deprecated and the new provider should be used instead.

See https://wiki.openssl.org/index.php/OpenSSL_3.0
1.6 Engines and "METHOD" APIs
The refactoring to support Providers conflicts internally with the APIs used to support engines, including the ENGINE API and any function that creates or modifies custom "METHODS" (for example EVP_MD_meth_new, EVP_CIPHER_meth_new, EVP_PKEY_meth_new, RSA_meth_new, EC_KEY_METHOD_new, etc.). These functions are being deprecated in OpenSSL 3.0, and users of these APIs should know that their use can likely bypass provider selection and configuration, with unintended consequences. This is particularly relevant for applications written to use the OpenSSL 3.0 FIPS module, as detailed below. Authors and maintainers of external engines are strongly encouraged to refactor their code transforming engines into providers using the new Provider API and avoiding deprecated methods.
